### PR TITLE
stat/distuv: fix call parameters for SuffStat

### LINKED ISSUE #177: stat/distuv: incorrect length of suffStat parameter passed Normal.Fit
For normal distribution, the suffstat obviously has a length of 2, with mu and sigma. But in the distuv/norm.go source code, the length of suffStat in the Fit method is set to 1. That causes a panic.

    func (n *Normal) Fit(samples, weights []float64) {

	    suffStat := make([]float64, 1)                  //HERE

	    nSamples := n.SuffStat(samples, weights, suffStat)

	    n.ConjugateUpdate(suffStat, nSamples, []float64{0, 0})

    }

I think that should be set to 2.

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

Fixes #177.

### CODE REVIEW

File: distuv/norm_test.go [hunk 1]
```diff
@@ -142,13 +141,23 @@ func TestNormalQuantile(t *testing.T) {
...
-		fmt.Println(math.Abs(got - ans[i]))
 		if !floats.EqualWithinAbsOrRel(got, ans[i], 1e-10, 1e-10) {
 			t.Errorf("Quantile mismatch. Case %d, want: %v, got: %v", i, ans[i], got)
 		}
 	}
 }
 
+func TestNormFitPanic(t *testing.T) {
+	n := Normal{Mu: 0, Sigma: 1}
+	func() {
```
Comment (vladimir-ch) [inline distuv/norm_test.go]: Missing defer.

File: distuv/exponential_test.go [hunk 2]
```diff
@@ -58,3 +58,14 @@ func TestExponentialScore(t *testing.T) {
 		testDerivParam(t, test)
 	}
 }
+
+func TestExponentialFitPanic(t *testing.T) {
+	e := Exponential{Rate: 2}
+	func() {
```
Comment (vladimir-ch) [inline distuv/exponential_test.go]: Missing defer.

File: distuv/exponential.go [hunk 3]
```diff
@@ -199,13 +200,13 @@ func (e Exponential) StdDev() float64 {
 // of the samples.
 //
 // If weights is nil, the weights are assumed to be 1, otherwise panics if
-// len(samples) != len(weights). Panics if len(suffStat) != 1.
+// len(samples) != len(weights). Panics if len(suffStat) != NumSuffStat().
 func (Exponential) SuffStat(samples, weights, suffStat []float64) (nSamples float64) {
```
Comment (vladimir-ch) [inline distuv/exponential.go]: A side note in case we want to stabilize the API one day: the destination slice is usually the first.

File: distuv/norm_test.go (hunk 1 above)
Comment (kortschak) [inline distuv/norm_test.go]: Thanks. Fixed.

File: distuv/exponential_test.go (hunk 2 above)
Comment (kortschak) [inline distuv/exponential_test.go]: Fixed.

File: distuv/exponential.go (hunk 3 above)
Comment (kortschak) [inline distuv/exponential.go]: Yeah. I think, in line with @btracey's request that I hold off on the factorisation matrix extraction revisions, that should probably wait until the monorepoisation has happened.

There should probably be an issue in gonum/gonum for that to aggregate issues https://github.com/gonum/gonum/issues/4.
